### ISSUE TITLE
Capitalization of Terms

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#184]
Issues with capitalization of terms, pertains to:
- -027
- -034
- -041
- -042
- -054
- -099

**-027 schemas for describing Observations	
Does "observations" need to be capitalized here? Please check and modify throughout if necessary.	

**-034 Observation	
"observation" and "measurement" are written in lowercase letters in this subclause, whereas elsewhere in the document they are capitalized. Please check whether or not these terms require a capital letter at the beginning and harmonize throughout.	

**-041 Well, Aquifer and FluidBody 	
Is it necessary for these terms to be written with capital letters here?	

**-042 domain features	
Note that at times "domain" is written with a capital letter, and at times not. Please verify which option is correct and harmonize throughout.	

**-054 Other examples of Sensors include the human eyes.	
Does "sensors" need to have a capital letter here? Please check and harmonize throughout the document.	

**-099 Observations, measurements and samples 	
Previously this has been written with each word capitalized. Please harmonize throughout.

**Comment by sgrellet** [comment]
My overall rationale would be to capitalize terms that correspond to a class in the model (Ex : Observation, Sample)

With this in mind I would say

* -027 schemas for describing Observations -> yes capitalization
* -034 Observation -> that's the hardest. With the rationale above that would end up in 'Observation and measurement'.
* -041 Well, Aquifer and FluidBody : I actually wrote them with OGC:GWML2 in mind where they are actual classes in the model.  We should just add what's in bold in this sentence "In this example, Well, Aquifer and FluidBody are modelled outside the OMS model **_(in OGC:GWML2)_** but: ..." and keep the capitalized letters.
* -042 domain features : I would keep 'domain' and 'Feature'
* -054 Other examples of Sensors include the human eyes : 'sensor'
* -099 Observations, measurements and samples : -> capitalized all way through because that's the name of the standard.

**Comment by KathiSchleidt** [comment]
Makes sense to me!

**Comment by ilkkarinne** [comment]
-099: please note that the ISO 19156 title is "Geographic information — Observations, measurements and samples". The OGC specification title is "Geographic information — Observations, Measurements and Samples". If I recall correctly, the title was lower-case in the CD Ballot stage by the ISO secretariat.

**Comment by ilkkarinne** [comment]
Hmm, we seem to have fixed the titles with only the "Observation" word capitalized in the SWG meeting of 9th June 2021: https://github.com/opengeospatial/om-swg/issues/89#issuecomment-857600461

**Comment by ilkkarinne** [comment]
ISO House Style has a section regarding capitalisation (https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-s-capitals):
"In titles and headings, only the first word is capitalized, except for proper nouns, acronyms or initialisms."

**Comment by KathiSchleidt** [comment]
So, title is Observations, measurements and samples.

**Comment by KathiSchleidt** [comment]
Pertaining to `5.2	Conformance classes related to models including Observations, Measurements and Samples`
Reduce to
`5.2	Conformance classes`

**Comment by sgrellet** [comment]
**-041 Well, Aquifer and FluidBody**


@KathiSchleidt 
Actually in OGC:GWML2 (https://docs.ogc.org/is/19-013/19-013.html#toc34) class names are prefixed with 'GW_' so that should be GW_Well, GW_Aquifer and GW_FluidBody.

I have searched we have 9 occurrence of Well including this one "EXAMPLE 2b)	Some common names for SpatialSample used in various application domains include Borehole, Flightline, Interval, Lidar Cloud, Map Horizon, Microscope Slide, Mine Level, Mine, Observation Well, Profile, Pulp, Quadrat, Scene, Section, ShipsTrack, Spot, Station, Swath, Trajectory, Traverse, etc.." (where everyone starts with a capital letter)

Proposal : In this example, Well, Aquifer and FluidBody are modelled outside the OMS model (in OGC:GWML2 respectively under GW_Well, GW_Aquifer and GW_FluidBody).

To avoid rewriting everything and also the follwing Figures (7 & 8) for non real value added (will just add more complexity for the reader)

**Comment by KathiSchleidt** [comment]
Added 
`respectively under GW_Well, GW_Aquifer and GW_FluidBody`
To the text under 7.3.2	Relationship between Sample and domain features. I'll leave the other capitalizations, naively assume that this statement early in the text covers the rest of the capital "Well" etc

**Comment by sgrellet** [comment]
Agreed
