### ISSUE TITLE
Object of Interest 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#21]
Created 2 sketches to better explain the CRP: http://ogc.standardstracker.org/attachment.cgi?id=48

ObservedProperty does not allow to separate the observable property from its object of interest
For example : for "massic concentration of NO3-", observableProperty = massic concentration & object of interest = NO3-

As a result in 10-004r3, in "observedProperty" registries we can end-up with a long list of every objectOfInterest concatenated with all its 'obervable properties'. For NO3- "object of interest" other observableProperties would be 'molar concentration', 'ppm'

To avoid exchanging this using om:parameter a dedicated property would be useful. This would also allow APIs to filter on it.

Example definition for an "objectOfInterest" property: "This vocabulary contains a set of substances and taxa which may appear as the subject (identified object) of some observable properties." (from"CSIRO Register: substances and taxa" 'http://registry2.it.csiro.au/def/object') also instantiated here ("BRGM Registre: Objets d'intérêts - Paramètres et substances" https://data.geoscience.fr/ncl/_ObjParSubs) with a definition in French (~ the English one)

With regard to the cardinality om:objectOfInterest (0,*). Supporting Use case
- observableProperty: mass concentation of 6 pesticides (URI to supporting registry entry)
- objectOfInterest : 6 URIs to those 6 pesticides in objectOfInterest registry
- procedure : "GC/MS (gas chromatography mass spectrometry)" (URI to supporting registry entry)

Source: http://ogc.standardstracker.org/show_request.cgi?id=608

**Comment by dr-shorthair** [comment]
Indeed, you can get a combinatorial explosion of observed properties when you consider all the chemical-species, organism, sensor etc. That's why [NVS P01](http://vocab.nerc.ac.uk/collection/P01/current/) has >30k entries! Having a predictable design pattern for compound-observables is useful here. 

Another solution is fuller use of the O&M model itself - e.g. the feature of interest is 'Nitrogen in the water column' ... (though arguably that just moves the same problem to a different place as each feature must get combined with every chemical substance, etc ...) So I would be cautious about adding more properties like 'object-of-interest', since this information already inheres in either the feature-of-interest or observed-property. 

Ultimately the best solution is likely to depend on the application and customary practice in a community.

**Comment by sgrellet** [comment]
@ilkkarinne  : ok to also be assigned to that issue

**Comment by KathiSchleidt** [comment]
I'm starting to see a parallel with the UltimateFeatureOfInterest #3 
Is this actually the UltimateObservedProperty?

**Comment by sgrellet** [comment]
After discussions in Toulouse and webconfs, there is a concensus from a a domain point of view to have this information.
The question that remains is how to model this. Various approaches are on the table. We have to discuss the proper IT mechanism to do so : cross-community and allowing communities to refine this based on their customary practices

**Comment by sgrellet** [comment]
Issue mainly taken on board by RDA I-ADOPT work.
See : https://www.rd-alliance.org/groups/interoperable-descriptions-observable-property-terminology-wg-i-adopt-wg
