### ISSUE TITLE
Remove Green Associations

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#212]
While the associations with inverse relatedObservation are now painted black in (most) diagrams, they seem to still be defined as green. When one imports the model with RAS (details at https://github.com/ISO-TC211/HMMG/wiki) and pastes in classes, the associations are still green.

Example: Association between conceptual Obs and Host

**Comment by ilkkarinne** [comment]
I cannot see the green line issue when editing the OMS model from the ISO Cloud directly using EA, perhaps the Reusable assets reflect an old copy of the model where the issue was there?

Styles when the Observation -> Host association is selected in Figure E.1 (green color selected):
 
<img width="785" alt="Screenshot 2022-09-22 at 12 35 06" src="https://user-images.githubusercontent.com/2580289/191714109-a51e3351-577e-425c-b2f3-6aabc0acdaa8.png">

Context menu -> Appearance.. -dialog when the Observation -> Host association is selected in Figure E.1 (default dark grey color selected):
<img width="461" alt="Screenshot 2022-09-22 at 12 36 22" src="https://user-images.githubusercontent.com/2580289/191714368-e150600f-c08a-438e-96c7-dc0b3078bcaf.png">

Styles when the Observation -> Host association is selected in Figure 9 (default dark grey color selected):
<img width="1139" alt="Screenshot 2022-09-22 at 12 37 09" src="https://user-images.githubusercontent.com/2580289/191714682-4c72834f-94ae-43c3-ac6f-053629b5ca3d.png">

Context menu -> Appearance.. -dialog when the Observation -> Host association is selected in Figure 9 (default dark grey color selected):
<img width="677" alt="Screenshot 2022-09-22 at 12 37 37" src="https://user-images.githubusercontent.com/2580289/191714745-f27b7aaa-f403-41e1-9e09-09dfea8a87e9.png">

Can someone repeat the issue when using the ISO Cloud connection directly, and not with Reusable Assets?

**Comment by KathiSchleidt** [comment]
Just did a quick check, looks good!

You're probably correct that this has to do with delays in propagating the model to RAS. I've now caught up on Conceptual Modelling Group mails on the OGC Cloud, feedback from Knut was very interesting. Here he states that he must manually do something to get models to RAS, the dates on OMS are August 8th.
