### ISSUE TITLE
Add Platform and Deployment

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#28]
related to #19 
would be valuable to differentiate between the monitoring facility and the sample

**Comment by ilkkarinne** [comment]
The [sosa:Platform](https://www.w3.org/TR/vocab-ssn/#SOSAPlatform) is related to [ssn:Deployment](https://www.w3.org/TR/vocab-ssn/#SSNDeployment). Deployment for a particular purpose may be done on a specific Platform. ssn:Deployment may link to 

- the hosted Systems (Observers, Sensors in our case),
- the Platform(s) used, and
- the property (the Observers can observe)

The sosa:Platform also links to the hosted Systems and the Deployments, but not the properties.

As far as I understand the ssn:Deployment may be either a more precise location (particular wall in a room, on a station (Platform) or define the purpose of the particular deployment the System (measurement campaign). 
  
Do we want to mimic these semantics in O&M?

**Comment by ilkkarinne** [comment]
In the Feb 26 2020 SWG meeting we decided not to include the System concept in the O&M model, because it really brings little or no additional value. The relation hosts/hostedBy would be directly between the Platform and the Observer. The relation implements/implementedBy between Procedure and System was dropped to be consistent with the intent to try limit the imported concepts to the SOSA ones and not include SSN ones unless really required.

**Comment by ilkkarinne** [comment]
The current draft UML model has a bi-directional association between the Observer and the Platform with cardinalities 0..* on the Observer side and 0..1 on the Platform side. This model cannot capture cases where the Observer moves from one Platform to another. If I remember correctly a similar issue was solved INSPIRE Environmental Monitoring Facilities application schema be introducing an intermediate class for the monitoring activity.

Should we add an association class for the Observer-Platform association with an optional time period attribute?

**Comment by ilkkarinne** [comment]
The Platform would probably be a highly domain specific feature: Observation station in some cases, a measurement campaign in others etc. It may be problematic to enforce using the abstract O&M Platform class as a super class of these feature types as they could already be domain features in their own class hierarchy.

What if we would do the same as with FoIs and make the platform association point to AnyFeature?

**Comment by ilkkarinne** [comment]
This is actually a more generic design decision: if we want to mandate that all concrete sub-classed of an abstract class has certain associations, we need to define those in the named abstract class instead of using AnyFeature. If we only define the "platform" semantics in the associations pointing towards the platform and otherwise leave its definition open, we can use AnyFeature and allow applications to use any existing platform feature they may have to act as the platform where the Observer points to.

**Comment by ilkkarinne** [comment]
Returned this into discussion since it was felt in the 1 Apr 2020 SWG meeting that Deployment class (and perhaps also System) was necessary for capturing observing campaigns etc. that are really not Platform instances. The revised UML model is available at https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-07_Observation.png

**Comment by KathiSchleidt** [comment]
How does Deployment and Platform really differ? What added value does Deployment provide?
Seems like Deployment is a further level of information on the association between System & Platform

We're looking for something to support the concept of a survey campaign, seems to fit better to Deployment than Platform, but this is the only use case we've found to date

**Comment by sgrellet** [comment]
To me, the notion of 'Observation Campaign' differs from Deployment and Platform. It's mentionned in :ssn:Deployment defintion but not modelled as a class. Maybe the lign between what is modelled in OM V3 and SOSA/SSN should not include ssn:Deployment (but include Platform with regards to Fig18 in SSN) and we should model ObservationCampaign on its own.

**Comment by ilkkarinne** [comment]
In the the [most recent draft UML model](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-05-08_Observation.png) there is a bi-directional association between the ```AbstractObserver (0..*)```  and the ```AbstractPlatform (0..*)``` with an association class ```Deployment```. The Deployment class has three attributes:

- ```definingResource: URI[0..1]```, 
- ```deploymentReason: CharacterString[0..*]``` and 
- ```deploymentTime: TM_Period[0..*]```

Both the Observer and Platform features are expected to have a life span extending before as well as considerably after the Observation event. The Observer may have earlier Platform Deployments which are not longer currents at the ```Observation.resultTime``` and the one current at the that time may be removed at some time after the Observation was made, like when a particular sensor is mounted on a different observation station, vessel etc. Matching the ```Deployment.deploymentTime``` with the ```Observation.resultTime``` or ```Observation.phenomenonTime``` provides information about which Platform the Observer was hosted on at the time of a particular Observation. 

The measurement campaign information is intended to be provided using the Deployment association class attributes. For the cases where a data provider does not wish to publish the deployment Platform information, but does want to provide the Deployment information, the Platform association end can be explicitly stated as missing (with xsi:nil=true for the XML implementation etc.)

**Comment by sgrellet** [comment]
> For the cases where a data provider does not wish to publish the deployment Platform information, but does want to provide the Deployment information, the Platform association end can be explicitly stated as missing (with xsi:nil=true for the XML implementation etc.)

I would understant this rationale from a Logical Model / implementation oriented point of view. 
But here we target a conceptual model.

The current model means you cannot have the Deployment of an Observer without assigning it to a Platform.
Which I find disturbing.

I think [ssn:Deployment ](https://www.w3.org/TR/vocab-ssn/#SSNDeployment)also goes that way (" Deployment **may** be done on a Platform.") and makes it a class on its own

**Comment by ilkkarinne** [comment]
The model used to have the Deployment as a class of it's own with 0..* associations to both Observer (via the now-gone AbstractSystem) and to Platform. This was turned into an association class because the Deployment was seen as inherently bound to a particular association between an Observer and a Platform. It was later discussed that in cases where the Platform is not provided, it can be provided as missing (nil/null).

If we would decide to move the Deployment as a separate class again, then I would suggest removing the AbstractObserver and AbstractPlatform from the core package, and the Observer, Deployment, Platform triad included in the Basic package

**Comment by ilkkarinne** [comment]
Based on the SWG discussion on 9th September, the UML model package Abstract observation core was changed regarding the association between the ```AbstractObserver```` and ```AbstractHost``` (super class of both ```AbstractPlatform``` and ```AbstractCampaign```): The ```Deployment``` association class is now an individual feature type class ```AbstractDeployment``` with (shared) aggregate single-direction 0..* associations from both ```AbstractObserver``` (role   deployment) and from ```AbstractHost``` (role deployedObserver). It also has single-direction associations to the ```Observer``` interface (role observer) with cardinality 1 and to ```Host``` interface (role host) with cardinality 0..1.

This construct allows any specialization of ```AbstractObserver``` to have zero or more specializations of ```AbstractDeployment```, each either with any realization of the Host interface or without a host. Vice versa any specialization of ```AbstractHost``` may have zero or more specializations of ```AbstractDeployment``` each with a mandatory association to any realization of the ```Observer``` interface. This means that implementations using the ```AbstractObserver``` class are may to include deployment with an optional host information without being forced to use the AbstractHost realization of the Host.
