### ISSUE TITLE
Update Sampling Features with SOSA Sampling

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#32]
While we've all been focusing on the observational end of O&M, we've neglected the SOSA reworking of the sampling features - https://www.w3.org/TR/vocab-ssn/#Sampling

I personally would prefer the full inclusion of SOSA Sampling, while at the same time NOT introducing a link between observation and samplingStrategy (not sure what this class represents) as all relevant sampling information should be attached to the FoI

Relevant spin-off of discussion #18

**Comment by ilkkarinne** [comment]
Hi, a draft of how the Sampling (extension) requirements class could extend the Observation core UML classes now available for discussion at https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/sampling_extension_uml_draft.png

**Comment by dr-shorthair** [comment]
Good - this pretty much matches [SOSA Sample](https://www.w3.org/TR/vocab-ssn/#Sampling-overview) 
Not that the essential property of a `Sample` is the relation `isSampleOf`.

**Comment by ilkkarinne** [comment]
I have now updated the first sketch on the Sampling model by @KathiSchleidt. The new version is based on the discussions in the June OGC Member meeting and on 22nd July SWG meeting. It reflects the SOSA Sample and Sampling concepts pretty closely, but does not (at least yet) contain the Sampler concept. The association roles between the Sampling and the Sample are ```sampling``` and ```sample``` instead of SOSA ```isResultOf``` and ```hasResult``` for consistency with the other proposed O&M association role naming.

Any comments most welcome, as we need to nail down the O&M Sampling model by the Aug 26 2020 (in one month).

See https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-07-23_Sampling_Specimen_overview.png

**Comment by sgrellet** [comment]
+1 on having the 3 classes :  Sample, Samping, Sampler and adjusted names for association roles

Reading [SOSA:Sample](https://www.w3.org/TR/vocab-ssn/#SOSASample) def  (as we don't have OM_V3 def yet), it seems our OM_V3:Sample maps to OM_V2:SF_SamplingFeature. Am I correct ?

But : 
- I don't understand the fact that PhysicalSample is now a subtype of SpatialSample (but I have missed couple summer webconfs). I have the feeling we are revisiting the entire OMV2 'Sampling Feature' 
Could we try to work out definitions for those guys to clarify understanding ?

**Comment by dr-shorthair** [comment]
Also, since there is no local precedent to match, perhaps rename `PhysicalSample` to `MaterialSample` to match OBI - http://purl.obolibrary.org/obo/OBI_0000747)
