### ISSUE TITLE
Observation Template

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#33]
I'm splitting the Observation Template discussion off from the Potential Observation #18 issue
The template is definitely pertinent to the Observation Collection #2 
It could also be relevant pertaining to Observation Specialization #27

**Comment by ilkkarinne** [comment]
A (hopefully) clarified description of the proposed use of an observation template to avoid unnecessary duplication of the identical property values for a collection of Observation instances is ive below.

A concrete Observation instance (A) could contain a reference to an instance of another observation instance (B) with class derived from AbstractObservation. The property name for this reference would be  "appliedTemplate" and it would have cardinality on 0..1.

The class of B would have to the same as the class A, or its super class. In the case the where this B contains the appliedTemplate reference to B, the set of properties and associations contained in B would be be evaluated as a template for the properties and associations of A with overriding semantics: 

- for a property or association contained only in B (with cardinality > 0): The value(s) of this property in B would also be applied to A as A directly contained these properties.
- for a property or association contained only in A (with cardinality > 0): No effect on A.
- for a property or association contained in both the A and B (with cardinality > 0) : No effect on A, the property values of B would be overridden by the values of A.

Perhaps a better word than template to use here would be cascaded observation?

Within the Observation collection context the observation cascading could be used to define the shared property and association values of a Observation instances within a collection instead of introducing a dedicated ObservationCollection: a template Observation instance would contain the shared property values and each the contained Observations would reference it using the appliedTemplate. There would be no need for a dedicated ObservationCollection class, a generic feature collection would suffice.

Foreseen benefits over the dedicated ObservationCollection (as proposed in [SSN-ext](https://www.w3.org/TR/vocab-ssn-ext/#sosa:ObservationCollection)):

- The Observation instances extracted from the collection would automatically retain the cascaded property values as the explicit upstream cascade link would remain as-is. In ObservationCollection the cascaded values are only implicitly linked to the contained Observation instances, and this link would be lost on extraction unless the shared values would be copied to the Observations on extraction.
- The cascading could be used more naturally as part of APIs using feature collection as the query result container: If the resource Observation dataset made available via a API would contain Observation with shared properties wrapped in ObservationCollections, the API providing a filtered set of these Observations would have to return a collection of ObservationCollections as the query results in order to maintain the shared properties. With the cascading, the API would return a regular feature collection with appliedTemplate references pointing to the Observation instance with the shared property values.

The downsides of the cascade:
- In cases where only a single (simple) property value is shared, the appliedTemplate reference and the separate template Observation would create more overhead than repeating the value for each Observation.
- Separate resolving step would be required to get the complete set of the Observation property values. It should be noted that a local resolving step (or in-context evaluation) is also required for shared property values of Observation instances contained within an ObservationCollection.

@KathiSchleidt commented in O&M SWG meeting held on 22 Jan 2020 that this would create a considerable new complexity in O&M v3 compared to v2, and suggested that at least there should be a straight-forward Observation class defined without the added cascading complexity. This could be solved by defining a (simple) Observation and a the CascadedObservation as separate classes with only the latter containing the optional appliedTemplate property and semantics as outlined above. The problem with this approach is that any derived Observation classes (in dedicated O&M application schemas) would have to choose either the simple or the cascaded Observation as the parent class to derive from, or they would have to implement a simple and a cascaded variant for each new Observation type.

This discussion will be continued in the O&M SWG meeting to be held on 29 Jan 2020.

**Comment by ilkkarinne** [comment]
After thinking through what @sgrellet noted in the 22 Jan SWG meeting, I agree that the cascade or templating to avoid repeating the same property values in a collection is largely an implementation issue, and not really part of the conceptual model. Also, as proposed by @sgrellet, the association from an Observation instance to the upstream cascade Observation instance could be modelled using the relatedObservation association with a specific role name. Thus appliedTemplate association is not necessary.

**Comment by KathiSchleidt** [comment]
Solved differently
