### ISSUE TITLE
featureOfInterest (fOI) association splitted into finer ones ?

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/om-swg#35]
Issue to keep track and clarify our common understanding of Toulouse TC Monday discussions (Nov.18th).
Are we all clear that the current (O&M v2) featureOfInterest (fOI) association role is to be split in two associations ?

- one to what was called ultimate fOI in many OM related discussions (and renamed in the latest om-swg discussions)
- and one to what was used as the '1st level' fOI often (not always) sampling related and pointing in turn to the 'domain' Feature that was monitored.

If yes, I'm going to close that issue and we'll have dedicated issues to refine the semantics of the two new associations.

**Comment by KathiSchleidt** [comment]
makes a lot of sense! I'm all for, and since nobody has complained over the last week, I see this as "no objections"
Only bit I'd like to add is that we already have #3  for Ufo (or whatever we decide to call it), so we only need one new issue for what I would much like to keep as featureOfInterest!!! (I do not see any argumentation for why this name causes issues. it's well established, is being reused in SOSA, thus no need to change just because we can ;) )

**Comment by sgrellet** [comment]
Thanks.
+1 on avoiding unnecessary renaming. 
Goes in the same direction as what Simon wrote in issue tracker 246 (see #3) : 'Introduce an additional (optional) property to link to the sampling strategy or feature; **reserve the feature-of-interest property to refer to only the ultimate domain feature whose property is being observed**.'

so we'll have 

- #3 : for the uFoI/FoI discussion
- and for the 'sampling part' ? would that be #32 or a more 'generic' one ? When this is clarified we can close this issue

**Comment by KathiSchleidt** [comment]
Shall we use https://docs.google.com/spreadsheets/d/1RbZtW8rDRk7n7oDoNH0SONPm1uZ29dkAPByXwddOvOY/edit#gid=0

**Comment by sgrellet** [comment]
As per discussion in 15.01.2020 SWG meeting.
SWG members agree to split OM V2 fOI association into 2 association to disambiguate the current 2 usage of that association.
We also need to break retro compatibility as minimum as possible
Issue is now what semantics we want for those 2 associations

2 solutions on the table
- A : 
	- 'fOI' : pointing to the 'domain' feature (ex : River section)
	- add another association to a 'sample' : could have some '**..sample..**' in its name
not to break fOI semantics

- B : 
	- 'fOI': pointing to a 'sample'
	- 'ultimateFoI' : pointing to the 'domain' feature (ex : River section)
not breaking current O&M V2 implementation which really often have the OMV2:fOI pointing to a sampling artefact

Discussion to be continued in next SWG telco also in the light of SSN-Ext about to go to next Public Working Draft (see https://github.com/opengeospatial/om-swg/issues/3#issuecomment-574599004).

**Comment by dr-shorthair** [comment]
I like to use the terminology 'proximate' and 'ultimate' FoI, since not every proximate FoI is a strict Sample.

**Comment by hylkevds** [comment]
And once we have the names chosen, we need to decide on which one to make mandatory.

**Comment by ilkkarinne** [comment]
To put @dr-shorthair's and @sgrellet's together, maybe options could be expanded to something like this:

- A:
   - property 'featureOfInterest/hasFeatureOfInterest' -> (ultimate) domain feature (ex: River) of type AnyFeature
   - property 'samplingFeature/sampling/hasSample' -> nearest sampling feature of type (abstract) Sample
- B:
   - property 'featureOfInterest/hasFeatureOfInterest' -> nearest sampling feature of type (abstract) Sample
   - property 'ultimateFeatureOfInterest/hasUltimateFeatureOfInterest' -> (ultimate) domain feature (ex: River) of type AnyFeature
- C:
   - property 'featureOfInterest/hasFeatureOfInterest' -> nearest proximate feature of type AnyFeature
   - property 'ultimateFeatureOfInterest/hasUltimateFeatureOfInterest' -> (ultimate) domain feature (ex: River) of type AnyFeature
- D:
   - property 'featureOfInterest/hasFeatureOfInterest' -> (ultimate) domain feature (ex: River) of type AnyFeature
   - property 'proximateFeatureOfInterest/hasProximateFeatureOfInterest' -> nearest proximate feature of type AnyFeature
- E:
   - property 'ultimateFeatureOfInterest/hasUltimateFeatureOfInterest' -> (ultimate) domain feature (ex: River) of type AnyFeature
   - property 'proximateFeatureOfInterest/hasProximateFeatureOfInterest' -> nearest proximate feature of type AnyFeature

**Comment by dr-shorthair** [comment]
I vote for C.

**Comment by lvdbrink** [comment]
I tend to agree that option C seems best. I'm checking this with Dutch O&M users and will get back with their feedback, if any.

**Comment by sgrellet** [comment]
We (BRGM) agree that
- proximateFOI is not always of type 'Sample'
-> this property should point to type= anyFeature
- ultimateFOI
-> this property should point to type= anyFeature
-> this is the 'new' property
- only question that remains then is semantic VS technical retrocompability
	- option C/ keeping the fOI property named 'fOI' and adjusting its def to include the term 'proximate'
	- option E/ renaming the property into 'proximateFOI' and includind the term 'proximate' in its def

In both cases to ensure a minimum of retrocompability we would have to map the new semantics to the previous ones.
Option C seems to have the least impact.
Intuitively we would go for C with the naming convention 'hasXXX' / 'isXXXof' we find in many SemanticWeb models (ex : SOSA)
But doing so we _de facto_ rename 'fOI' property into another one ('hasFOI') !
-> So wouldn't it be possible to also take that opportunity to insert the term 'proximate' for the sake of clarity (forcing people to tell wich fOI there are talking about when modelling) ?

-> Thus we vote for option E 'hasProximateFeatureOfInterest' 
One would tell that it also breaks SOSA O&M AlignmentModule but it will have to be updated anyway.

**Comment by KathiSchleidt** [comment]
As we are splitting the semantics of the FoI relation, we believe it is safer to create two new association names - Option E
Reasoning: as the semantics have changed from V2, there is a danger that users familiar with V2 will just continue to reuse the FoI relation, although the semantics no longer apply
By providing proximate vs ultimate FoI, on the one hand the user can easily find the new relations while being forced to reflect the semantics of what they're trying to express

**Comment by sgrellet** [comment]
Summarizes well today's SWG meeting discussion

**Comment by sgrellet** [comment]
the hasXXX, isXXXof aspect of the issue concerns all the standard. will be discussed under issue #38

**Comment by sgrellet** [comment]
after SWG meeting 22/01/2020 : issues related to Sensors are not part of the xxxFoI issue they will be discussed under #30

**Comment by sgrellet** [comment]
after SWG meeting 22/01/2020 : issue tagged 'Initial decision' -> will be tagged 'Final decision' in 2 weeks SWG meeting unless strong objection

**Comment by dr-shorthair** [comment]
I disagree that the semantics have changed. 

FoI was always the _proximate_ FoI. 

What has changed is that we have added a link to the ultimate-FoI alongside, which just makes it more obvious that the original was to the proximate, but does not actually change its meaning. Go back through the various iterations of O&M and I think you'll find it was consistently proximate.

**Comment by cportele** [comment]
My preference would have been C, too, but E is fine as well. It is also my understanding that `proximateFeatureOfInterest` has the same semantics as `featureOfInterest` in the current version. 

The advantages that I saw in C compared with E:
* since it is essentially the same role there is no need to change the name;
* with increasing complexity of the terms, the model becomes harder to understand for newcomers.

But it is just a name choice, so E works, too, as I said.

**Comment by KathiSchleidt** [comment]
@dr-shorthair while I totally agree with you that the semantics of FoI have formally not changed, informally, the practical use has been semantically all over. Within real-world O&M V2 implementations, the FoI can be found to reference:

1. The Object the Observation was made on (so something sample-like, what I'd expect under FoI, proposed in V3 as **ProximateFoI** in order to separate from the following 2 options)
2. Some higher level domain feature (the river the sample was taken from, now the **UltimateFoI**)
3. The facility where the measurement was taken (this one really hurt, though I understand the pragmatic background. Reason I also pushed for **Platform**)

The logic for creating new names comes from experience in other domains where concepts are eternally split and lumped while maintaining some of the naming. Later the data users get all upset that one cannot differentiate the differing concepts described by the same name (think biodiversity, species taxonomies...)

Also - if we leave FoI and add other stuff, we're worried that data providers will ignore the other stuff and continue with their skewed semantics

**Comment by sgrellet** [comment]
With regards the semantics, we have a different reading. 
From 19156:2011: 'Domain' definition is "_The association Domain shall link the OM_Observation to the GFI_Feature (C.2.1) that is the subject of the observation and carries the observed property. This feature has the role featureOfInterest with respect to the observation. **This feature is the real-world object whose properties are under observation, or is a feature intended to sample the real-world object,** as described in Clause 9 of this International Standard. An observation instance serves as a propertyValueProvider for its feature-of-interest_"

In V3 we are currently discussing splitting the sentence in bold into two different properties. Thus taking out a part of the previous definition. For us this is a change of semantics

**Comment by dr-shorthair** [comment]
'the real-world object whose properties are under observation' is not inconsistent with it being the _proximate_ FoI - I wrote the definition quoted above, and that was my intention. The second part of the sentence was _clarification_, in the sense 'sometimes it is a sample', not an alternative secondary option.

**Comment by ilkkarinne** [comment]
I have to admit I had always interpreted the Domain association as one pointing to any kind of FoI, proximate in the case the data provider had intended to make the proximation process visible, or ultimate if not. I think I'm right to say I'm not the only one with this interpretation.

Regardless of what was intended in the O&M 2.0 spec, there are numerous implementation models, datasets and APIs out there which use the featureOfInterest role to point to an ultimate FoI directly provide no association to any proximate FoI. It this sense it unfortunately does not really matter what the original intention of in the spec was. With the addition of the optional ultimate FoI role in the next version,  they most likely leave everything as-is, because the old property name is still there (in probably does not occur to them that they had mis-interpreted the 2.0 spec, and there could now be a clarified description of the association in the new spec as the name remains the same). This will probably create a lot of confusion with the data users, as they rightly assume that the featureOfInterest role in an O&M 3.0 data always points to a proximate FoI regardless of the dataset they are accessing.

As I see it we have two options to try and harmonise the the pattern to point to FoIs in the new model:

1. Keep using the ```featureOfInterest``` role name for the association to  point to the proximateFoI (if one exists) and try very very hard to make all the migrating O&M users  actually read the new spec instead of just assuming that they already have things in order.
2. Use a new name that is close enough to the old to easily discover it (without reading the spec) but different enough that a brief WTF moment happens resulting in them googling the semantics of the proximateFeatureOfInterest and the ultimateFeatureOfInterest (what, there are now two FoIs???).

**Comment by lvdbrink** [comment]
I opt for option 1 (and stick to my vote for option C in the earlier proposed options). If we replace the role name ``featureOfInterest`` we are 'punishing' those users who have been using this role correctly, to point to the proximate FOI. I strongly suggest we should not existing change role names unless we really, really have to.

**Comment by ilkkarinne** [comment]
After discussion the O&M SWG decided in the 5 Feb meeting to proceed with the option E (```proximateFeatureOfInterest``` role name instead of ```featureOfInterest```) as the OGC change proposal for ISO 19156. The SWG also decided that concrete use cases demonstrating likely interoperability issues caused by sticking with the  name```featureOfInterest``` will be linked to this issue, and that O&M SWG will take action in ensuring harmonisation the proximate/ultimate FoI terminology with SOSA.
