### ISSUE TITLE
Information as attributes instead of elements

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#50]
How can we specify that specific attributes (pertaining to association classes) are to be modeled as XML attributes instead of defining an association class with elements?
It would be far better aligned with the other ISO models to provide information on roles and linking times in this manner

**Comment by ilkkarinne** [comment]
@cportele: Is there something we need to do already in the UML modelling phase (like specific tagged values) if we want to prefer map  association class attributes into GML attributes instead of turning the association class into XML elements for a complex type and the related propertyType?

We have the Observation and Platform context classes in mind especially, but perhaps also the Deployment association class. I'm not exactly sure how the GML-with-attributes should look like in these cases, but we just want to know if we can postpone thinking about this until the revision of the GML implementation spec and not limit our GML implementation options unintentionally at this point. 

See https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-28_Observation.png

**Comment by cportele** [comment]
In the Observation and Platform context classes it seems to me that the intent would be better expressed with association qualifiers than an association class. `sourceRole` and `targetRole` are really qualifiers of the respective association ends, not properties of the association itself. 

If you use ShapeChange for the conversion to XSD, the qualifiers are mapped to XML attributes with conversion rule [rule-xsd-prop-qualified-associations]( https://shapechange.net/targets/xsd/extensions/#rule-xsd-prop-qualified-associations).

This is different in the Deployment case and an association class seems appropriate here. However, I fail to see how this could be mapped to XML attributes with multiplicities greater than 1.

**Comment by ilkkarinne** [comment]
Thanks @cportele, makes sense. Association classes now removed for Observation and Platform contexts and replaced by association qualifiers: https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-29_Observation.png
