### ISSUE TITLE
ObservationBasic:FeatureOfInterest FeatureType

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/om-swg#64]
This [new class](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-08-21_Basic_Observations_overview.png) is a placeholder for system/people that don't have proximate, ultimateFoI domain features modeled somewhere.

I understand the need to explain things to people and help them understand/apply the model (but examples in annexes could help as well :) )

* FoI is a role not a class, to me that's an implementation level placeholder artefact we are looking for. 
For example, I guess we could add it in an updated OM V3 XML document
* we are on a conceptual model. In a open world assumption approach I would not override locally what ISO 19103 is allowing

I the group wants to keep it 
* should this class be renamed DomainPlaceholder or something around this ?
* is 19109:AnyFeature realizing (or something else) the 19103:Any ? Otherwise we may need to add the Domain, DomainProxy, Range associations
* do we need to redefine that a 19109:FT can have a location (or is that added at GML level) ?
* link attribute should be type URL and URI (apparently we don't want to provide the URI to the FoI here)

**Comment by ilkkarinne** [comment]
The SWG members decided that a concrete feature type to use as the target of the ```ultimateFeatureOfInterest``` role should be retained in the Basic observations package. However the name ```FeatureOfInterest``` was not optimal as it describes the role rather than the target. I renamed the FeatureOfInterest class first to ```DomainFeature``` and subsequently to ```GenericDomainFeature``` to highlight it's intended use as a fallback class if no appropriate domain feature was available in the application domain.
