### ISSUE TITLE
Any interface (19103) vs Any featureType (19109)

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#66]
Is there a formal link between interface Any from 19103 and Any featureType from 19109? 

For the interfaces defined within 19156 we have added Realizes associations between the interface and the abstract featureType realizing the class. However, we do not have the mandate to modify the specifications laid down in 19103 and 19109.

Is some equivalent already in place? Should such an equivalent be in place? Is this an issue due to the fact that the use of interfaces in OGC/ISO Conceptual Models is still new and a bit unclear???

**Comment by jetgeo** [comment]
There is no link between the ISO 19103 "Any" type (interface) and the ISO 19109 "AnyFeature" FeatureType as they are totally different concepts: A data type and a feature type. 

The "Any" type (interface) is an abstract concept for a data type. A data type defines the value domain for a property (attribute or association end). "Any" "_represents the universal root type which can be used as a root or base type in the type definition hierarchy. Any can be seen as an implicit supertype of all other types. This use of Any is not strictly consistent with the semantics of the UML metamodel._ " (!). In other words, a realization of "Any" as a data type defines that a property can contain any kind of value.  

The "AnyFeature" class is the core generalization of all feature types and represents abstractions of real-world phenomena. A feature type may, of course, have properties that have value domain "Any". Or any other data type.

**Comment by ilkkarinne** [comment]
Hi @jetgeo, Is there a clause in 19103 which states that "The "Any" type (interface) is an abstract concept for **a data type**" (my emphasis)? This is very important for us because, if a realization of Any is always a dataType, it cannot have a separate identity or a separate life span from the feature that has it as the value of its property. This would completely break the current O&M conceptual model, as we use Any as the target of many of our associations (metadata, result, proximateFeatureOfInterest and ultimateFeatureOfInterest) for maximum implementation flexibility (the target does not have to be a Feature as per 19109).

**Comment by jetgeo** [comment]
Clause 7 of ISO 19103:2015 specifies a set of core data types, and "Any" is one of them. So: yes, "Any" is a data type and cannot exist on its own. 
However, it can very well be the target of an association, as an association role is a property just like an attribute. For example, an XML implementation treats attributes and association roles as the same concept. 
You cannot define a Featuretype as a realization of the Any interface, as they represent different concepts from the UML metamodel. If your associations are meant to refer to something that can exist on its own, the AnyFeature class would be a better option, as all feature instances are members of the set represented by that class.

**Comment by ilkkarinne** [comment]
Ok, thanks @opengeospatial/coverageprocessanalytics-project_team 

Based on this information I'm proposing the following changes:

- Make the target of both feature-of-interest associations AnyFeature instead of Any again
- Change the associations result, metadata and resultQuality attributes of type Any instead of associations to Any (mainly for diagram clarity, but also to highlight the fact that they are pointing data types

I might still investigate the possibility of defining a union of Any and AnyFeature for the result, as the coverage (feature) valued Observations results are an important use case for O&M, while in many cases an anonymous simple data type result is what is needed

**Comment by sgrellet** [comment]
@ilkkarinne : +1

> `I might still investigate the possibility of defining a union of Any and AnyFeature for the result, as the coverage (feature) valued Observations results are an important use case for O&M`

agreed, was also following that line of thoughts when reading your proposed changes

**Comment by jetgeo** [comment]
Agree, a union of the two concepts seems like a good approach. An implementation can then use either a simple datatype or a feature type as the value domain for the association.

**Comment by KathiSchleidt** [comment]
@ilkkarinne 
Further confirming that we must be able to support features as Result, could also be a geometry
I don't quite understand your second point - changing Any to Any? ;) please clarify!

**Comment by ilkkarinne** [comment]
@KathiSchleidt: my second point was about changing associations into attributes for the resultQuality and metadata. Since pointing to Any would be pointing to a DataType anyway (could only have them related by a composition association), we may as well use attributes there and save a lot of those messy association lines in the diagrams.

**Comment by KathiSchleidt** [comment]
@ilkkarinne ok, then I understood correctly
Shifting resultQuality and metadata to an attribute (quality was originally an attribute anyway) works for me and makes the diagram simpler.
But, we do need to be able to support both data and featureTypes at least for metadata - otherwise we rule out references to 19115. Just checking 19157 to figure out what type DQ_Element is (as a standard candidate) - interesting is that here it is just of type "Class" (hmm....?)

**Comment by ilkkarinne** [comment]
@KathiSchleidt: MD_Metadata in 19115 is not a feature, so Any could encompass it, right?

**Comment by KathiSchleidt** [comment]
@ilkkarinne True - just checked, MD_Metadata is just a datatype
But, if we have the union type because we need it for Result and DataQuality anyway - why not use it?
Fear I'm still a bit lost in the OGC world on features vs. non-features, hoping that on API level we find a better balance in providing both spatial and non-spatial objects in a harmonized manner - until this is resolved, would be good if we can support both types

**Comment by sgrellet** [comment]
Changes discussed are fine in the 'Core' package but we still have an issue in the 'Abstract' one (in O&M webconf right now).
In the [latest version of Abstract](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/Abstract_Observation_schema_overview_latest.png), our <<interface>> Observation now points to 190103:Any for domain (fOI) & range (result).

But : based on the discussion above, 190103:Any is a datatype which is not not what we  want for fOI and result (it's too restrictive). Which also makes us loose consistency between Abstract and Core; Abstract becoming more restrictive than Core (where we point to 19019 FeatureType)

@jetgeo : Don't we have an 'Any identifiable object' to point to in 19103 ?
Something that would enable us to point to like, [owl:Thing](https://www.w3.org/TR/owl-guide/) in WebSem ("...Every individual in the OWL world is a member of the class owl:Thing...")

**Comment by jetgeo** [comment]
Any identifiable object can be an instance of a FeatureType that is a subtype of AnyFeature. It is described in ISO 19109 that all feature instances are members of the set represented by AnyFeature. However, the instance needs to be of a non-abstract FeatureType. If you need a directly implementable class, you may want to create a specific one for your standard, as AnyFeature is abstract.

**Comment by KathiSchleidt** [comment]
Nice, but what do we do for cases where we do NOT wish to point to a feature? In many cases the target will be a feature, but we must also be able to support cases where the target does NOT come from the OGC Spatial world. Thus, we'd like a true ANY somehow above AnyFeature.
Help!

**Comment by sgrellet** [comment]
- Abstract package tries to be at the same meta level as 19103
- and Core tries to be at the same meta level as 19109
and we try to avoid mixing those meta levels

**Comment by jetgeo** [comment]
@KathiSchleidt : I believe a union of the datatype Any and a class for any feature would solve that. However, as pointed out by @sgrellet, AnyFeature (and the stereotype FeatureType) is at the ApplicationSchema level. So perhaps you need to define a specific interface for a identifiable object in your abstract model and realize it as a featuretype in the application schema? The members of the union would then be the Any interface and your new interface.

**Comment by KathiSchleidt** [comment]
@jetgeo our worry is then when it comes to encoding this will require excess baggage. 
Example is the Result of an observation, in the final encoding we'd like the result association/attribute thingy to point directly to the result. From what I've seen under GML encodings, the union would require a more complex XPath:
* we'd like result/Measure
* with Union, think we get result/ObservationResult/featureValue/Measure
Any way of avoiding this down the road?

**Comment by ilkkarinne** [comment]
I would add the fact that in O&M 2.0 (ISO 19156:2011) the Range (result) association of OM_Observation is a (composition) association to Any (from ISO/TS 19103:2005), even though the 19156 introduces a OM_DiscreteCoverageObservation with the (redefined?) result association (by composition, again) pointing to CV_DiscreteCoverage from ISO 19123 Edition 1.

I guess formally this means that the coverage provided as a result or OM_Observation is owned by the OM_Observation and cannot exist independently (due to the composition), although in practice these coverages probably have had an independent lifespan from the Observation that created them.

We want to be able to point to a Coverage instance as the result of an Observation as well as use an Observation instance as the value of a Coverage metadata description.

**Comment by jetgeo** [comment]
@KathiSchleidt : I can understand that you want to avoid the extra level the Union introduces. This is one of the downsides with XML and GML. 

Perhaps we have made this to complicated ;). 
Practically, as the value of "Any" can be anything, it can also be (the value of) a feature instance. The feature instance can exist on its own with an identity. But when it is used as the value of "Any", it is formally considered only a value. So I suppose you could use only "Any". 

@ilkkarinne : I would say the meaning of a composition is a bit different for a data type than for a class. A composition to a class means that the "whole" class "owns" the  "part" class. An instance of the "part" can exist on its own, but it can only be connected to (owned by) one "whole" at a time. Think of a car and its wheels. The wheels can exist and be used by (owned by) any car, but only on one car at a time. For a data type, the association goes to a value, which formally has no life outside of the association. But that doesn't mean that the feature cannot exist outside of the association.

**Comment by ilkkarinne** [comment]
@jetgeo: ok, we I would propose we got with Any for the result then, as it was in the Edition 1.

To make sure I understand the how the Any valued properties work I would like you to confirm that the following three UML declarations have the same meaning, and that we can use the one which makes more sense diagram clarity wise for ```AbstractObservationCharacteristics```:

1. An attribute ```+ result: Any[0..*]```
1. An composition association with out-going role ```result```` and cardinality of ```0..*``` pointing to ```Any```
1. A regular association with out-going role ```result```` and cardinality of ```0..*```  pointing to ```Any``` (keeping in mind that all instances of Any are data types)

**Comment by cportele** [comment]
@jetgeo @ilkkarinne - Sorry for chiming in late, but I do not understand why `Any` would be restricted to data types. As 19103 states, "Any can be seen as an implicit super type of all other types". This includes feature types and other classes and classifiers, too, including `AnyFeature`, not just data types.

**Comment by jetgeo** [comment]
@ilkkarinne : I agree that the three declarations have the same meaning for practical use. 

@cportele : Thank you, it's never to late! The starting point for the discussion was about a formal link between Any and AnyFeature. Any is defined in clause 7 in 19103, which deals with data types. That's why I consider Any to be a data type, not a class. But as I have commented above, the value of Any can of course be a feature instance.

**Comment by cportele** [comment]
@jetgeo - The clause is called "data types", but since everything in the clause is modelled as an interface, none of these types are data types in the sense of the UML meta model. I guess it would have been clearer to use a different term.

@ilkkarinne - As a result, for me the options 2 and 3 do not have the same meaning. In option 3 the `Any` instances are not owned by `AbstractObservationCharacteristics `.

**Comment by jetgeo** [comment]
@cportele Sure, the 19103 data types are modelled as interfaces, which means they are not formal UML data types. But in the scope of 19103, I am quite sure they are meant to be realized as data types. However, the value can still be a feature instance. 
The difference between option 2 and 3 is whether a `result` can be assigned to several `AbstractObservationCharacteristics` or not.

**Comment by ilkkarinne** [comment]
Coming back to the originating question of this thread am I summarizing the discussion correctly by stating that @cportele and @jetgeo disagree on whether ```AnyFeature``` (or any other feature type) is allowed to realize the ```Any``` interface?

Considering the ownership: I think we cannot live with ```AbstractObservationCharacteristics``` owning it's result Any. The ```AbstractObservationCharacteristics``` is specialized, among other things, as the ObservationCharacteristics class in the Basic package, which is used in ObservationCollection collection instances to capture the shared properties of the collection members. The result Any may well be one of these shared properties, and thus associated with many Observation collection members.

**Comment by jetgeo** [comment]
On the ownership: From your description, you should then use option 1 or 3, which are equivalent. 

On ´Any´ and ´AnyFeature´: I suppose that's a correct observation (or measurement ;)), but I believe we agree on the use. From a pure UML point of view, there is nothing wrong with realizing the interface ´Any´ as a feature type such as ´AnyFeature´. But in the context of ISO 19103, I think it shall be considered as a data type. But then again, as described, it can be used for the value of a feature instance. So it's not really a problem.

**Comment by ilkkarinne** [comment]
@jetgeo: I thought the attribute semantically equalled composition rather than aggregation (or just a generic association)?

**Comment by cportele** [comment]
@ilkkarinne - that is what I remember, but I did not immediately find the source for this in UML 2 (but this document is way too big/complex anyhow for searching). In any case, there is no way in EA that I know of to specify the aggregation type for an attribute and composition seems to be the best default for most attributes. I would use a regular association.

**Comment by jetgeo** [comment]
Agree with @cportele . Concerning both the UML documentation and the prefered association type. 
The way I see it, and I may be totally wrong: When the value domain for the attribute or association is a data type, it doesn't really matter. It is just a value and may be duplicated on the attributes or association roles of many feature instances. 
More generally, I find it natural that an attribute equals a regular association, as I don't know any way to define the aggregation type for an attribute. But I may be wrong.

**Comment by ilkkarinne** [comment]
Could we have the metadata properties as attributes everywhere? This single change would make the diagrams considerably more readable.

I guess that would mean that the metadata descriptions would be considered as owned by the source class.
