### ISSUE TITLE
URI vs URL

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#67]
The old conundrum of URI vs URL - which should we use for an attribute providing a link to an external resource? 
Can one provide a DOI as a URL, or would we need to support URI?
Thoughts???

**Comment by ilkkarinne** [comment]
This issue is related to to the ```link``` attributes of ```ObservingProcedure```, ```ObservedProperty```, ```Observer```, ```Host``` and ```DomainFeature``` classes in the Basic package. The idea for these classes is to have simple, concrete classes there to be implemented by the O&M encodings as ready-to-use entities if no concrete realizations for the Procedure, ObservedProperty, Observer, Host and Any as the feature-of-interest already exist on the application schema. The ```link``` attributes would be used to point to remote resources describing these class instances mitigating the limited expression richness of the classes themselves.

I do see a few issues here: Firstly, the mechanism described above is far for the conceptual model level of abstraction. I would rather se this kind of linking as an implementation level issue. Secondly, the name ```link``` is really generic. Thirdly the URL classifier exists in ISO 19115 (metadata) in package "Citation and responsible party information". I would really not like to introduce a dependency to ISO 19115 for this as we are just getting rid of it for the metadata association.
