### ISSUE TITLE
Definitions for the key classes

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#96]
MB/NC: AU01-009-010
Line number: 
Clause/Subclause: 3
Paragraph/Figure/Table: 
Type of comment: te 
Comments: Definitions for the key classes defined in this standard should be included in the Terms and Definitions section, in particular
- Observation
- Observer
- Procedure
- Sensor
- Sample
- Sampler
- Feature-of-interest
- Proximate feature-of-interest
- Ultimate feature-of-interest

------------------------------------------

MB/NC: DK-010-011
Line number: 
Clause/Subclause: 3
Paragraph/Figure/Table: 
Type of comment: Te 
Comments: Given that the title of this standard is “Observation and measurement”, it might be appropriate also to include the word “observation” along with the already existing “**measurement**”.
Proposed change: Add “measurement” to clause 3. The definition of the word can be found in the 2011 version of the standard.

------------------------------------------

MB/NC: DK-011-012
Line number: 
Clause/Subclause: 3
Paragraph/Figure/Table: 
Type of comment: ge 
Comments: Certain key concepts are not present in the ”Terms and definitions”. As the terms and definitions are freely available to – and searchable for - anyone via ISO’s online browser platform and Geolexica, it is important that the key concepts of the standard are present there.
Proposed change: Add “sampling location”, “feature-of-interest”, “ultimate feature-of-interest”, “principal location of interest”, “proximate feature-of-interest”, “sampled feature” and any other key concepts to the “Terms and Definitions”.

**Comment by KathiSchleidt** [comment]
General comment: will add definitions for all classes contained in the 2 conceptual models

**Comment by ilkkarinne** [comment]
Difficult to come up with short textual definitions for the concepts in the Terms and definitions, and to avoid conflicts with requirement clauses and UML

**Comment by KathiSchleidt** [comment]
Is it possible to input relevant concepts from O&M (including the requirements) to Geolexica without adding them all to Terms and Definitions

**Comment by ReesePlews** [comment]
hello @KathiSchleidt,  regarding your question about adding terms to Geolexica.... at this time, such an option is not allowed because of the requirements for Geolexica (terminology entries from clause 3 from current ISO/TC211 published standards).  the format of terminology entries in clause 3 strictly follows the ISO/IEC Directives Part 2 and also other terminology standards, mainly ISO 10241-1, so adding the names of classes, attributes, and other "components" of the uml models can be difficult because of the regular terminology formatting requirements. 

most of the standards TC211 develops do not add terminology entries in clause 3 for the UML diagrams.  they are typically described in the document. @ilkkarinne is correct that structuring such descriptions into clause 3 terminology entries can be difficult.   clause 3 will hold more of the overall terms and definitions for helping to understand the concepts of the document. 

also, please remember that if you define a term in clause 3, you must use it in the document. 

in the future there will be a way to more easily create a registry of terms that exist outside of a standard but at this time, we cannot easily do that. TMG is working towards that.  

please let me know if you have any other questions and i will try and answer them. thank you

**Comment by KathiSchleidt** [comment]
Based on this feedback, I would propose:

- Not adding definitions for concepts defined within the standard itself to the definitions (our original approach, questioned by the comments listed above)
- Waiting for whatever registry-like-construct TMG comes up with

We will continue to pursue options to expose the individual requirements with their definitions via an OGC resource, to allow for referencing of all concepts defined.

@ReesePlews what would interest me is how Geolexica will deal with the existing O&M based definitions. At present a lot of the concepts from the previous version of 19156 are included, e.g. "observation". If we don't define these terms in the revision, will the old ones be removed or maintained for posterity?

Also - is there any way to input requirement to the group working on a new structure? Would be nice if our approach of providing atomic referenceable requirements could be included

**Comment by KathiSchleidt** [comment]
ISO Clause that definitions cannot be redefined in normative text

**Comment by ReesePlews** [comment]
hello @KathiSchleidt, Geolexica can be thought of as an online-mirror of the Multi Lingual Glossary of Terms (MLGT). In the MLGT superseded terms are maintained. 

as an example, please see: "coordinate set" 
current valid entry: https://isotc211.geolexica.org/concepts/2353/
superseded entry:  https://isotc211.geolexica.org/concepts/729/

The content of the MLGT comes directly from the Terminology Repository (repo) which is managed by the TMG. The MLGT is updated less frequently approximately 2-4 years because it gave time to the NBs for translation of the entries. 

Additionally, there is another standing document that could be helpful for you. Approximately every 3 months the current content (selected attributes) from the repo is output and circulated to the TC members as an Ndoc called the "Terminology Spreadsheet". version 68 will soon be available to the TC members through the ndoc archive. in my understanding if you are an OGC member you should have access to those files. please find the most current set (#68) and examine when you have time. All terms (drafts, and published) developed by TC211 are contained in those documents. 

Do you have access to some other standards that TC211 developed? Those documents can be very helpful to understand the document structure and content of presenting normative text and the models. These are available on the TC211 ndocs site. 

When you have clause 3 ready please send me and i will have a look.

Please let me know if there are other terminology questions and i will try to answer.

**Comment by KathiSchleidt** [comment]
Will be decided at the bitter end

**Comment by ronaldtse** [comment]
@KathiSchleidt this is an interesting issue! This is an issue that is problematic within ISO, not only with TC 211. @ReesePlews, myself and a few other ISO experts are aware of this.

The problem is about how to organize, link and manage different layers of semantic interoperability. In ISO, Clause 3 should only contain general language concepts (and only authored in English).

UML class names, codes, etc can be considered "interpreted concepts" or "implementation concepts" that "relate" to the general concepts. This means that the "general concepts" and the "implementation concepts" exist on separate ontological layers, and these two layers should be documented separately.

Today ISO does not have any provision for documenting the second layer (or even deeper layers) of concepts. This is something @ReesePlews and I are trying to achieve in ISO SMART, but this is not something that will have a quick ETA.

In the meantime, we are closer to making this happen in the Glossarist software and Geolexica. Let's consider this topic "on hold" and we shall get back to you on this.

**Comment by PeterParslow** [comment]
"Generically" I'd say that the TC211 approach has been to use Clause 3 (or 4?) for "general terms", with the UML model (through the published Harmonised Model) providing the definition of terms that primarily appear in the UML model. For example, ISO 19101 has always defined "feature"; ISO 19109 accepts that definition and goes on to define a metaclass FeatureType. So 'feature' appears in the MLGT / GeoLexica (https://isotc211.geolexica.org/concepts/168/) but "FeatureType" does not.

This relates well to a discussion we're having in TC211. We want to establish a register of "useful classes" (based initially on those in ISO 19103 Annex C, like "CharacterString"). That's "at the UML level". But those classes are implementations of concepts, so it would be great to relate them (in the model and/or in this new register) to the concepts - preferably identified with a well managed HTTP URI. That would also be helpful for generating better TC211 ontology outputs; these currently provide an OWL class for each class in the UML model, whereas some ontology users expect them to define concepts (the rules for generating those classes are under revision). Reese, Ron: this came up in our "Ad hoc" looking at non-relational databases, at which Kathi presented & so did a "non geo" philosophical ontologist...

Until that's all resolved (and perhaps afterwards!), I think the approach that Reese & Ronald have outlined is correct: stuff defined in the model stays in the model & 'other terms' go in the Terms & Definitions clause.

**Comment by KathiSchleidt** [comment]
As the terms proposed for definitions are all classes defined within the standard, we do not define them as terms to avoid redundant definitions. It would be most welcome if GeoLexica could also integrate definitions ensuing from requirements or other concepts not defined within the terms and definitions section.
We'd like to avoid putting the entire standard in section 3

**Comment by KathiSchleidt** [comment]
Definitions closely aligned to the requirements texts to be added to a separate terms&defs subsection as agreed with ISO terminology group

**Comment by KathiSchleidt** [comment]
Comment to Carl Reed - definitions (list at top of this issue) have been added to clause 3.2 Internal Definitions, need to check that the alignment with the definitions from the requirements of these classes are aligned
